# Generated by Django 5.2.13 on 2026-04-29 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleto',
            name='ip_dispositivo',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
