# Generated by Django 5.2.13 on 2026-04-30 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_tickets', '0002_boleto_ip_dispositivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boleto',
            name='ip_dispositivo',
        ),
        migrations.AddField(
            model_name='boleto',
            name='identificador_invitado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
